# Generated by Django 2.2.1 on 2019-09-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_investment_respondent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emailsperday',
            new_name='q1answer',
        ),
        migrations.AddField(
            model_name='user',
            name='q2answer',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='q3answer',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='q4answer',
            field=models.CharField(default='', max_length=25),
        ),
    ]
